/*
 * AppClaudeBuddy — Mooncake app implementation
 */
#include "app_claude_buddy.h"

#include <hal/hal.h>
#include <mooncake_log.h>
#include <assets/assets.h>
#include <smooth_lvgl.hpp>
#include <stackchan/stackchan.h>
#include <apps/common/common.h>
#include <esp_heap_caps.h>
#include <sys/time.h>
#include <cstdio>
#include <cctype>
#include <algorithm>
#include <cstdlib>
#include <cmath>
#include <ctime>

using namespace mooncake;
using namespace stackchan;
using namespace smooth_ui_toolkit::lvgl_cpp;
using namespace ArduinoJson;

static const std::string_view TAG = "AppClaudeBuddy";

// ── Constructor ───────────────────────────────────────────────────────────────

AppClaudeBuddy::AppClaudeBuddy()
{
    setAppInfo().name = "Buddy";

    // Generated by tools/make_buddy_icon.py → assets/assets_bin/icon_claude_buddy.bin
    static auto icon  = assets::get_image("icon_claude_buddy.bin");
    setAppInfo().icon = (void*)&icon;

    static uint32_t theme_color = THEME_PRIMARY;
    setAppInfo().userData       = (void*)&theme_color;
}

// ── Lifecycle ─────────────────────────────────────────────────────────────────

void AppClaudeBuddy::onCreate()
{
    mclog::tagInfo(TAG, "onCreate");
}

void AppClaudeBuddy::onOpen()
{
    mclog::tagInfo(TAG, "onOpen");

    _store.load();
    _store.loadDays();

    {
        LvglLockGuard lock;

        auto avatar = std::make_unique<avatar::DefaultAvatar>();
        avatar->init(lv_screen_active());
        avatar->getPanel()->onClick().connect([this]() { _screen_clicked = true; });
        GetStackChan().attachAvatar(std::move(avatar));

        GetStackChan().addModifier(std::make_unique<BreathModifier>());
        GetStackChan().addModifier(std::make_unique<BlinkModifier>());
        GetStackChan().addModifier(std::make_unique<HeadPetModifier>());
        GetStackChan().addModifier(std::make_unique<ImuEventModifier>());  // "dizzy" on shake

        GetStackChan().avatar().setSpeech("Starting BLE...");

        createUi();
        view::create_home_indicator([this]() { close(); }, THEME_PRIMARY, THEME_DARK);
        view::create_status_bar(THEME_PRIMARY, THEME_DARK);
    }

    // Head touch: approve while a prompt is pending, otherwise just activity
    _head_touch_conn = GetHAL().onHeadPetGesture.connect([this](HeadPetGesture g) {
        if (g == HeadPetGesture::Press) _head_pressed = true;
    });

    // Advertise as "Claude StackChan-XXXX" (desktop filters on the "Claude" prefix)
    std::string mac    = GetHAL().getFactoryMacString();
    std::string suffix = mac.size() >= 4 ? mac.substr(mac.size() - 4) : mac;
    for (auto& c : suffix) c = static_cast<char>(toupper(static_cast<unsigned char>(c)));
    buddy::BuddyLink::instance().start("Claude StackChan-" + suffix);

    _last_activity_ms = GetHAL().millis();
    setMood(Mood::Sleep, true);
}

void AppClaudeBuddy::onRunning()
{
    auto& link   = buddy::BuddyLink::instance();
    uint32_t now = GetHAL().millis();

    // ── Drain protocol lines ─────────────────────────────────────────────────
    {
        std::string line;
        int budget = 8;  // bound work per loop
        while (budget-- > 0 && link.takeLine(line)) {
            handleLine(line);
        }
    }

    // ── Link liveness → base mood ────────────────────────────────────────────
    // Re-read the clock: a snapshot handled above stamps a time later than `now`
    // and the unsigned subtraction would wrap and flag the bridge as dead.
    now           = GetHAL().millis();
    bool ble_up   = link.isConnected();
    uint32_t age  = _has_snapshot ? (now - _last_snapshot_ms) : 0;
    bool linked   = ble_up && _has_snapshot && age < LINK_TIMEOUT_MS;
    if (linked != _was_linked) {
        _was_linked = linked;
        if (!linked) {
            mclog::tagInfo(TAG, "bridge lost → sleep (ble={} snap={} age={}ms)", ble_up, _has_snapshot, age);
            _has_snapshot = false;
            _level        = -1;
            // Count a nap only after a real session (avoid NVS wear on brief flaps)
            if (now - _linked_since_ms > 10000) {
                _store.nap++;
                _store.saveStats();
            }
            _transient_active = false;
        } else {
            mclog::tagInfo(TAG, "bridge alive");
            _linked_since_ms = now;
            noteActivity("bridge alive");
            buddy::play_sfx(buddy::Sfx::Connect);
        }
    }

    // ── Link status feedback (speech bubble while asleep) ────────────────────
    {
        int st = static_cast<int>(link.linkStatus());
        int pf = link.pairFailures();
        if (st != _last_link_status || pf != _last_pair_failures) {
            _last_link_status   = st;
            _last_pair_failures = pf;
            noteActivity("link status");
            LvglLockGuard lock;
            refreshSpeech();
        }
    }

    // ── Pairing passkey ──────────────────────────────────────────────────────
    {
        uint32_t pk = link.pendingPasskey();
        if (pk != _shown_passkey) {
            _shown_passkey = pk;
            noteActivity("passkey");
            LvglLockGuard lock;
            showPasskey(pk);
        }
    }

    // ── Input flags ──────────────────────────────────────────────────────────
    bool screen_click  = _screen_clicked.exchange(false);
    bool head_pressed  = _head_pressed.exchange(false);
    bool approve_click = _approve_clicked.exchange(false);
    bool deny_click    = _deny_clicked.exchange(false);
    bool overlay_click = _overlay_clicked.exchange(false);

    // The capacitive head sensor fires on its own every few minutes (servo idle
    // motion), so head touches do not count as activity for the clock/dim timers.
    if (screen_click || approve_click || deny_click || overlay_click) {
        noteActivity(screen_click ? "screen tap" : approve_click ? "approve btn" : deny_click ? "deny btn"
                                                                                                : "overlay tap");
        if (_clock_shown) {
            LvglLockGuard lock;
            showClock(false);
            screen_click = false;  // the tap only dismissed the clock
        }
    }

    if (_snap.prompt.present) {
        // Head-pet approves only for non-dangerous prompts, and never in the first
        // 1.5 s (the "look up" servo move can tickle the capacitive head sensor).
        bool head_ok = head_pressed && _prompt_risk != Risk::Danger &&
                       (now - _prompt_seen_ms) >= HEAD_APPROVE_GRACE_MS;
        if (head_pressed && !head_ok) {
            mclog::tagInfo(TAG, "head touch ignored ({})",
                           _prompt_risk == Risk::Danger ? "danger prompt: use the button" : "too soon after prompt");
        }
        if (approve_click || head_ok) decide(true);
        else if (deny_click) decide(false);
    }

    if (overlay_click) {
        LvglLockGuard lock;
        showOverlay(false);
    } else if (screen_click && !_snap.prompt.present) {
        LvglLockGuard lock;
        showOverlay(!_overlay || _overlay->hasFlag(LV_OBJ_FLAG_HIDDEN));
    }

    if (_overlay_until && now >= _overlay_until) {
        LvglLockGuard lock;
        showOverlay(false);
    }

    // ── Transient mood expiry ────────────────────────────────────────────────
    if (_transient_active && now >= _transient_until) {
        _transient_active = false;
    }

    // ── Turn text expiry ─────────────────────────────────────────────────────
    if (_turn_until && now >= _turn_until) {
        _turn_until = 0;
        _turn_text.clear();
        LvglLockGuard lock;
        refreshSpeech();
    }

    // ── Resolve effective mood ───────────────────────────────────────────────
    setMood(_transient_active ? _transient : baseMood());

    // ── Clock mode: nothing happening for a while → show the time ───────────
    {
        // Signed, fresh-clock difference: noteActivity() may have stamped a time
        // later than this loop's `now`, and an unsigned wrap would flash the clock.
        int32_t idle_ms = static_cast<int32_t>(GetHAL().millis() - _last_activity_ms);
        bool quiet = (_mood == Mood::Idle || _mood == Mood::Sleep) && !_snap.prompt.present &&
                     idle_ms >= static_cast<int32_t>(CLOCK_AFTER_MS) && localDate() != 0;
        if (now - _idle_log_tick >= 5 * 60000) {
            _idle_log_tick = now;
            mclog::tagInfo(TAG, "idle check: mood={} prompt={} idle_for={}s clock={}", moodName(_mood),
                           _snap.prompt.present, idle_ms / 1000, _clock_shown);
        }
        if (quiet != _clock_shown) {
            LvglLockGuard lock;
            showClock(quiet);
        } else if (_clock_shown && now - _clock_tick >= 15000) {
            LvglLockGuard lock;
            updateClock();
        }
    }

    // ── Persist daily history (throttled) ───────────────────────────────────
    if (_days_dirty && now - _last_days_save_ms >= DAYS_SAVE_EVERY_MS) {
        _last_days_save_ms = now;
        _days_dirty        = false;
        _store.saveDays();
    }

    // ── Attention: escalation + look at the person ───────────────────────────
    if (_mood == Mood::Attention && _snap.prompt.present) {
        updateAttention();
    }

    // ── Animations ───────────────────────────────────────────────────────────
    updateLeds();
    updateCelebrateWiggle();
    checkDim();

    // ── LVGL update ──────────────────────────────────────────────────────────
    {
        LvglLockGuard lock;
        GetStackChan().update();
        view::update_home_indicator();
        view::update_status_bar();
    }
}

void AppClaudeBuddy::onClose()
{
    mclog::tagInfo(TAG, "onClose");

    GetHAL().onHeadPetGesture.disconnect(_head_touch_conn);
    _head_touch_conn = -1;

    buddy::LookTracker::instance().stop();
    if (_days_dirty) {
        _store.saveDays();
        _days_dirty = false;
    }
    GetHAL().showRgbColor(0, 0, 0);
    if (_dimmed) {
        GetHAL().setBackLightBrightness(75);
    }

    {
        LvglLockGuard lock;
        clearTransientModifiers();
        destroyUi();
        GetStackChan().resetAvatar();
        view::destroy_home_indicator();
        view::destroy_status_bar();
    }

    // NimBLE cannot be re-initialised in-process: warm-reboot back to the launcher
    GetHAL().requestWarmReboot(0);
}

// ── Protocol ──────────────────────────────────────────────────────────────────

void AppClaudeBuddy::handleLine(const std::string& line)
{
    JsonDocument doc;
    auto err = deserializeJson(doc, line);
    if (err) {
        mclog::tagWarn(TAG, "bad json ({}): {}", err.c_str(), fit(line, 80));
        return;
    }
    JsonObjectConst obj = doc.as<JsonObjectConst>();
    if (obj.isNull()) {
        return;
    }

    if (obj["cmd"].is<const char*>()) {
        handleCommand(obj);
        return;
    }
    if (obj["time"].is<JsonArrayConst>()) {
        handleTimeSync(obj["time"].as<JsonArrayConst>());
        return;
    }
    if (obj["evt"].is<const char*>()) {
        handleTurn(obj);
        return;
    }
    if (obj["total"].is<int>() || obj["msg"].is<const char*>() || obj["tokens"].is<unsigned long>()) {
        handleSnapshot(obj);
        return;
    }

    mclog::tagWarn(TAG, "unhandled message: {}", fit(line, 80));
}

void AppClaudeBuddy::handleSnapshot(JsonObjectConst doc)
{
    Snapshot s;
    s.total        = doc["total"] | 0;
    s.running      = doc["running"] | 0;
    s.waiting      = doc["waiting"] | 0;
    s.msg          = doc["msg"] | "";
    s.tokens       = doc["tokens"] | 0UL;
    s.tokens_today = doc["tokens_today"] | 0UL;

    JsonArrayConst entries = doc["entries"].as<JsonArrayConst>();
    if (!entries.isNull()) {
        for (JsonVariantConst e : entries) {
            if (e.is<const char*>()) {
                s.entries.emplace_back(e.as<const char*>());
                if (s.entries.size() >= 6) break;
            }
        }
    }

    JsonObjectConst p = doc["prompt"].as<JsonObjectConst>();
    if (!p.isNull() && p["id"].is<const char*>()) {
        s.prompt.present = true;
        s.prompt.id      = p["id"].as<const char*>();
        s.prompt.tool    = p["tool"] | "";
        s.prompt.hint    = p["hint"] | "";
    }

    uint32_t now = GetHAL().millis();

    // Track when a given prompt was first shown (for the 5 s "heart" reward)
    if (s.prompt.present) {
        if (s.prompt.id != _prompt_seen_id) {
            _prompt_seen_id   = s.prompt.id;
            _prompt_seen_ms   = now;
            _last_reminder_ms = now;
            _prompt_risk      = assessRisk(s.prompt.tool, s.prompt.hint);
            mclog::tagInfo(TAG, "approval pending ({}): {} — {}",
                           _prompt_risk == Risk::Danger ? "DANGER" : _prompt_risk == Risk::Caution ? "caution" : "ok",
                           s.prompt.tool, s.prompt.hint);
            buddy::play_sfx(buddy::Sfx::Attention);
            if (_mood == Mood::Attention) {
                _snap.prompt = s.prompt;
                setMood(Mood::Attention, true);  // re-style for the new prompt's risk
            }
        }
    } else {
        _prompt_seen_id.clear();
    }

    // Level up every 50K cumulative tokens (baseline on first snapshot)
    int lvl = static_cast<int>(s.tokens / TOKENS_PER_LEVEL);
    if (_level < 0) {
        _level = lvl;
    } else if (lvl > _level) {
        _level = lvl;
        mclog::tagInfo(TAG, "level up → {}", lvl);
        buddy::play_sfx(buddy::Sfx::LevelUp);
        startTransient(Mood::Celebrate, TRANSIENT_MS);
    }

    // Per-day history: keep the day's token high-water mark
    if (uint32_t d = localDate()) {
        auto& t = _store.today(d);
        if (s.tokens_today > t.tokens) {
            t.tokens    = s.tokens_today;
            _days_dirty = true;
        }
    }

    _snap             = std::move(s);
    _has_snapshot     = true;
    _last_snapshot_ms = now;

    LvglLockGuard lock;
    refreshSpeech();
    refreshOverlay();
}

void AppClaudeBuddy::handleTurn(JsonObjectConst doc)
{
    const char* evt = doc["evt"] | "";
    if (std::string_view(evt) != "turn") {
        return;
    }
    const char* role = doc["role"] | "";
    if (std::string_view(role) != "assistant") {
        return;
    }

    JsonArrayConst content = doc["content"].as<JsonArrayConst>();
    if (content.isNull()) {
        return;
    }
    for (JsonVariantConst block : content) {
        const char* type = block["type"] | "";
        if (std::string_view(type) == "text" && block["text"].is<const char*>()) {
            _turn_text  = fit(block["text"].as<const char*>(), 56);
            _turn_until = GetHAL().millis() + TURN_SHOW_MS;
            LvglLockGuard lock;
            refreshSpeech();
            break;
        }
    }
}

void AppClaudeBuddy::handleTimeSync(JsonArrayConst arr)
{
    if (arr.size() < 1) {
        return;
    }
    long long epoch = arr[0] | 0LL;
    long offset     = arr.size() > 1 ? (arr[1] | 0L) : 0L;
    if (epoch <= 0) {
        return;
    }

    // POSIX TZ strings are "west-positive": UTC-7 → "BUD+7:00"
    long west   = -offset;
    char sign   = west < 0 ? '-' : '+';
    long absw   = std::labs(west);
    char tz[24] = {0};
    snprintf(tz, sizeof(tz), "BUD%c%ld:%02ld", sign, absw / 3600, (absw % 3600) / 60);
    setenv("TZ", tz, 1);
    tzset();

    struct timeval tv = {.tv_sec = static_cast<time_t>(epoch), .tv_usec = 0};
    settimeofday(&tv, nullptr);
    GetHAL().syncSystemTimeToRtc();

    mclog::tagInfo(TAG, "time synced: {} tz={}", epoch, tz);
}

void AppClaudeBuddy::handleCommand(JsonObjectConst doc)
{
    std::string cmd = doc["cmd"].as<const char*>();

    if (cmd == "status") {
        sendStatus();
    } else if (cmd == "name") {
        _store.name = doc["name"] | _store.name.c_str();
        _store.saveNames();
        sendAck("name", true);
    } else if (cmd == "owner") {
        _store.owner = doc["name"] | "";
        _store.saveNames();
        mclog::tagInfo(TAG, "owner: {}", _store.owner);
        sendAck("owner", true);
        if (!_store.owner.empty()) {
            _turn_text  = "Hi " + fit(_store.owner, 20) + "!";
            _turn_until = GetHAL().millis() + 4000;
            LvglLockGuard lock;
            refreshSpeech();
        }
    } else if (cmd == "unpair") {
        buddy::BuddyLink::instance().dropBonds();
        sendAck("unpair", true);
    } else if (cmd == "char_begin" || cmd == "file" || cmd == "chunk" || cmd == "file_end" || cmd == "char_end") {
        // GIF character packs target the StickC screen; Stack-Chan renders its own avatar.
        sendAck(cmd.c_str(), false, 0, "character packs not supported on Stack-Chan");
    } else {
        mclog::tagWarn(TAG, "unknown cmd: {}", cmd);
        sendAck(cmd.c_str(), false, 0, "unknown command");
    }
}

void AppClaudeBuddy::sendAck(const char* cmd, bool ok, int n, const char* error)
{
    JsonDocument doc;
    doc["ack"] = cmd;
    doc["ok"]  = ok;
    doc["n"]   = n;
    if (error) {
        doc["error"] = error;
    }
    std::string out;
    serializeJson(doc, out);
    buddy::BuddyLink::instance().sendLine(out);
}

void AppClaudeBuddy::sendStatus()
{
    JsonDocument doc;
    doc["ack"] = "status";
    doc["ok"]  = true;

    JsonObject d = doc["data"].to<JsonObject>();
    d["name"]    = _store.name;
    d["sec"]     = buddy::BuddyLink::instance().isEncrypted();

    JsonObject bat = d["bat"].to<JsonObject>();
    bat["pct"]     = GetHAL().getBatteryLevel();
    bat["usb"]     = GetHAL().isBatteryCharging();

    JsonObject sys = d["sys"].to<JsonObject>();
    sys["up"]      = GetHAL().millis() / 1000;
    sys["heap"]    = heap_caps_get_free_size(MALLOC_CAP_INTERNAL);

    JsonObject st = d["stats"].to<JsonObject>();
    st["appr"]    = _store.appr;
    st["deny"]    = _store.deny;
    st["vel"]     = _store.vel;
    st["nap"]     = _store.nap;
    st["lvl"]     = _level < 0 ? 0 : _level;

    std::string out;
    serializeJson(doc, out);
    buddy::BuddyLink::instance().sendLine(out);
}

void AppClaudeBuddy::sendPermission(const std::string& id, bool approve)
{
    JsonDocument doc;
    doc["cmd"]      = "permission";
    doc["id"]       = id;
    doc["decision"] = approve ? "once" : "deny";
    std::string out;
    serializeJson(doc, out);
    buddy::BuddyLink::instance().sendLine(out);
}

void AppClaudeBuddy::decide(bool approve)
{
    if (!_snap.prompt.present) {
        return;
    }
    uint32_t now      = GetHAL().millis();
    uint32_t reaction = now - _prompt_seen_ms;
    mclog::tagInfo(TAG, "{} {} after {} ms", approve ? "APPROVE" : "DENY", _snap.prompt.id, reaction);

    sendPermission(_snap.prompt.id, approve);
    buddy::play_sfx(approve ? buddy::Sfx::Approve : buddy::Sfx::Deny);

    if (approve) {
        _store.appr++;
        if (reaction < FAST_APPROVE_MS) {
            _store.vel++;
            startTransient(Mood::Heart, TRANSIENT_MS);
        }
    } else {
        _store.deny++;
    }
    _store.saveStats();
    if (uint32_t d = localDate()) {
        auto& t = _store.today(d);
        if (approve) t.appr++; else t.deny++;
        _store.saveDays();
        _days_dirty = false;
    }

    // Clear locally; the next snapshot is authoritative
    _snap.prompt = Prompt{};
    _prompt_seen_id.clear();
    LvglLockGuard lock;
    refreshSpeech();
}

// ── Mood / avatar ─────────────────────────────────────────────────────────────

AppClaudeBuddy::Mood AppClaudeBuddy::baseMood() const
{
    if (!_was_linked) return Mood::Sleep;
    if (_snap.prompt.present) return Mood::Attention;
    if (_snap.running > 0) return Mood::Busy;
    return Mood::Idle;
}

void AppClaudeBuddy::startTransient(Mood mood, uint32_t durationMs)
{
    _transient        = mood;
    _transient_active = true;
    _transient_until  = GetHAL().millis() + durationMs;
}

void AppClaudeBuddy::clearTransientModifiers()
{
    auto& sc = GetStackChan();
    if (_idle_motion_id >= 0) { sc.removeModifier(_idle_motion_id); _idle_motion_id = -1; }
    if (_idle_expr_id   >= 0) { sc.removeModifier(_idle_expr_id);   _idle_expr_id   = -1; }
    if (sc.hasAvatar()) {
        if (_sweat_id >= 0) { sc.avatar().removeDecorator(_sweat_id); _sweat_id = -1; }
        if (_heart_id >= 0) { sc.avatar().removeDecorator(_heart_id); _heart_id = -1; }
    }
}

void AppClaudeBuddy::setMood(Mood mood, bool force)
{
    if (!force && mood == _mood) {
        return;
    }
    mclog::tagInfo(TAG, "mood {} → {}", moodName(_mood), moodName(mood));
    bool was_attention = (_mood == Mood::Attention);
    _mood              = mood;

    // Camera tracker lives only while a prompt is pending (outside the LVGL lock:
    // stop() waits for an in-flight capture)
    if (was_attention && mood != Mood::Attention) {
        buddy::LookTracker::instance().stop();
    }
    if (mood == Mood::Attention && !was_attention) {
        buddy::LookTracker::instance().start();
        _last_look_step_ms = 0;
        _last_sweep_ms     = GetHAL().millis();
    }

    LvglLockGuard lock;
    auto& sc = GetStackChan();
    clearTransientModifiers();
    showDecisionButtons(mood == Mood::Attention);

    auto& av = sc.avatar();
    av.mouth().setWeight(0);

    switch (mood) {
        case Mood::Sleep:
            av.setEmotion(avatar::Emotion::Sleepy);
            av.mouth().setWeight(10);
            sc.motion().moveWithSpeed(0, 0, 80);
            GetHAL().showRgbColor(0, 0, 0);
            break;

        case Mood::Idle:
            av.setEmotion(avatar::Emotion::Neutral);
            _idle_motion_id = sc.addModifier(std::make_unique<IdleMotionModifier>());
            _idle_expr_id   = sc.addModifier(std::make_unique<IdleExpressionModifier>());
            GetHAL().showRgbColor(0, 0, 0);
            break;

        case Mood::Busy:
            av.setEmotion(avatar::Emotion::Neutral);
            _sweat_id       = av.addDecorator(std::make_unique<avatar::SweatDecorator>(lv_screen_active(), 0, 700));
            _idle_motion_id = sc.addModifier(std::make_unique<IdleMotionModifier>(6000, 10000));
            break;  // LEDs: breathing blue in updateLeds()

        case Mood::Attention:
            switch (_prompt_risk) {
                case Risk::Danger:
                    av.setEmotion(avatar::Emotion::Sad);
                    av.mouth().setWeight(30);
                    _sweat_id = av.addDecorator(std::make_unique<avatar::SweatDecorator>(lv_screen_active(), 0, 400));
                    break;
                case Risk::Caution:
                    av.setEmotion(avatar::Emotion::Doubt);
                    _sweat_id = av.addDecorator(std::make_unique<avatar::SweatDecorator>(lv_screen_active(), 0, 700));
                    break;
                case Risk::None:
                    av.setEmotion(avatar::Emotion::Doubt);
                    break;
            }
            sc.motion().moveWithSpeed(0, 320, 300);  // look up at the user
            break;  // LEDs: blink by risk in updateLeds()

        case Mood::Celebrate:
            av.setEmotion(avatar::Emotion::Happy);
            av.mouth().setWeight(70);
            _wiggle_tick = 0;
            break;  // LEDs: rainbow, head wiggle in updateCelebrateWiggle()

        case Mood::Heart:
            av.setEmotion(avatar::Emotion::Happy);
            av.mouth().setWeight(40);
            _heart_id = av.addDecorator(std::make_unique<avatar::HeartDecorator>(lv_screen_active(), 0, 400));
            GetHAL().showRgbColor(70, 0, 30);
            break;
    }

    refreshSpeech();
}

void AppClaudeBuddy::refreshSpeech()
{
    // Must be called with LvglLockGuard held.
    auto& sc = GetStackChan();
    if (!sc.hasAvatar()) return;
    auto& av = sc.avatar();

    switch (_mood) {
        case Mood::Sleep: {
            auto& link = buddy::BuddyLink::instance();
            if (link.pendingPasskey() != 0) {
                av.setSpeech("Type this code on your Mac");
                return;
            }
            switch (link.linkStatus()) {
                case buddy::LinkStatus::Advertising:
                    av.setSpeech("Zzz  (waiting for Claude)");
                    break;
                case buddy::LinkStatus::Connected:
                    av.setSpeech("Mac connected, securing link...");
                    break;
                case buddy::LinkStatus::Encrypted:
                    av.setSpeech("Secure link up, waiting for data...");
                    break;
                case buddy::LinkStatus::PairFailed: {
                    char buf[48];
                    snprintf(buf, sizeof(buf), "Pairing failed %d/3\nold key on the Mac?", link.pairFailures());
                    av.setSpeech(buf);
                    break;
                }
                case buddy::LinkStatus::IdentityRotated:
                    av.setSpeech("New identity!\nConnect me again on the Mac");
                    break;
            }
            return;
        }
        case Mood::Attention:
            if (_snap.prompt.present) {
                std::string tool = _snap.prompt.tool.empty() ? "this" : _snap.prompt.tool;
                std::string t;
                switch (_prompt_risk) {
                    case Risk::Danger:  t = "DANGER! " + tool; break;
                    case Risk::Caution: t = "Careful: " + tool + "?"; break;
                    case Risk::None:    t = "Approve " + tool + "?"; break;
                }
                if (!_snap.prompt.hint.empty()) t += "\n" + fit(_snap.prompt.hint, 36);
                av.setSpeech(t);
            } else {
                av.setSpeech("Approve?");
            }
            return;
        case Mood::Celebrate: {
            char buf[32];
            snprintf(buf, sizeof(buf), "Level %d!", _level < 0 ? 0 : _level);
            av.setSpeech(buf);
            return;
        }
        case Mood::Heart:
            av.setSpeech("Thanks!");
            return;
        case Mood::Busy:
        case Mood::Idle:
            break;
    }

    if (_turn_until && !_turn_text.empty()) {
        av.setSpeech(_turn_text);
    } else if (_mood == Mood::Busy && !_snap.msg.empty()) {
        av.setSpeech(fit(_snap.msg, 40));
    } else {
        av.setSpeech("");
    }
}

static void hue_to_rgb(uint16_t h, uint8_t v, uint8_t& r, uint8_t& g, uint8_t& b)
{
    h %= 360;
    uint8_t region = h / 60;
    uint8_t rem    = (h % 60) * 255 / 60;
    uint8_t q      = v - (uint32_t)v * rem / 255;
    uint8_t t      = (uint32_t)v * rem / 255;
    switch (region) {
        case 0:  r = v; g = t; b = 0; break;
        case 1:  r = q; g = v; b = 0; break;
        case 2:  r = 0; g = v; b = t; break;
        case 3:  r = 0; g = q; b = v; break;
        case 4:  r = t; g = 0; b = v; break;
        default: r = v; g = 0; b = q; break;
    }
}

void AppClaudeBuddy::updateLeds()
{
    uint32_t now = GetHAL().millis();
    if (now - _led_tick < 100) {
        return;
    }
    _led_tick = now;

    switch (_mood) {
        case Mood::Busy: {
            // slow blue breathing
            float phase = (now % 3000) / 3000.0f * 2.0f * 3.14159f;
            uint8_t v   = static_cast<uint8_t>(8 + 32 * (0.5f + 0.5f * sinf(phase)));
            GetHAL().showRgbColor(0, v / 3, v);
            break;
        }
        case Mood::Attention: {
            bool escalated  = (now - _prompt_seen_ms) >= ESCALATE_AFTER_MS;
            uint32_t period = escalated ? 180 : 400;
            bool on         = ((now / period) % 2) == 0;
            if (!on) {
                GetHAL().showRgbColor(0, 0, 0);
            } else if (_prompt_risk == Risk::Danger) {
                GetHAL().showRgbColor(110, 0, 0);
            } else if (_prompt_risk == Risk::Caution) {
                GetHAL().showRgbColor(100, 18, 0);
            } else {
                GetHAL().showRgbColor(90, 40, 0);
            }
            break;
        }
        case Mood::Celebrate: {
            uint8_t r, g, b;
            _hue = (_hue + 36) % 360;
            hue_to_rgb(_hue, 70, r, g, b);
            GetHAL().showRgbColor(r, g, b);
            break;
        }
        default:
            break;  // static colours set in setMood()
    }
}

void AppClaudeBuddy::updateCelebrateWiggle()
{
    if (_mood != Mood::Celebrate) {
        return;
    }
    uint32_t now = GetHAL().millis();
    if (now - _wiggle_tick < 350) {
        return;
    }
    _wiggle_tick  = now;
    _wiggle_phase = !_wiggle_phase;
    LvglLockGuard lock;
    GetStackChan().motion().moveWithSpeed(_wiggle_phase ? 260 : -260, 220, 450);
}

void AppClaudeBuddy::updateAttention()
{
    uint32_t now      = GetHAL().millis();
    uint32_t elapsed  = now - _prompt_seen_ms;
    bool     escalated = elapsed >= ESCALATE_AFTER_MS;

    // Escalation: nag every 30 s once the prompt has been ignored for a minute
    if (escalated && now - _last_reminder_ms >= REMINDER_EVERY_MS) {
        _last_reminder_ms = now;
        mclog::tagInfo(TAG, "prompt unanswered for {} s — reminding", elapsed / 1000);
        buddy::play_sfx(buddy::Sfx::Reminder);
    }

    // Look at the person: step the yaw toward the motion centroid
    int offset = 0;
    auto& tracker = buddy::LookTracker::instance();
    if (tracker.target(offset, LOOK_TARGET_AGE_MS)) {
        _last_sweep_ms = now;  // seeing someone cancels the search sweep
        if (now - _last_look_step_ms >= LOOK_STEP_MS && tracker.takeTarget(offset, LOOK_TARGET_AGE_MS)) {
            _last_look_step_ms = now;
            if (std::abs(offset) >= 15) {
                LvglLockGuard lock;
                auto& motion = GetStackChan().motion();
                if (!motion.isModifyLocked()) {
                    auto cur = motion.getCurrentAngles();
                    int yaw  = std::clamp(cur.x + LOOK_YAW_SIGN * offset * 4, -700, 700);
                    mclog::tagInfo(TAG, "look: offset={} yaw {} → {}", offset, cur.x, yaw);
                    motion.moveWithSpeed(yaw, 320, 420);
                    buddy::LookTracker::instance().suppress(LOOK_SETTLE_MS);
                } else {
                    mclog::tagInfo(TAG, "look: offset={} but motion locked", offset);
                }
            }
        }
        return;
    }

    // Nobody seen for a while and the prompt is stale: sweep left/right looking for them
    if (escalated && now - _last_sweep_ms >= SWEEP_EVERY_MS) {
        _last_sweep_ms = now;
        _sweep_dir     = !_sweep_dir;
        LvglLockGuard lock;
        auto& motion = GetStackChan().motion();
        if (!motion.isModifyLocked()) {
            motion.moveWithSpeed(_sweep_dir ? 380 : -380, 300, 200);
            buddy::LookTracker::instance().suppress(LOOK_SETTLE_MS + 600);
        }
    }
}

AppClaudeBuddy::Risk AppClaudeBuddy::assessRisk(const std::string& tool, const std::string& hint)
{
    std::string s = tool + " " + hint;
    for (auto& c : s) c = static_cast<char>(tolower(static_cast<unsigned char>(c)));
    auto has = [&](const char* needle) { return s.find(needle) != std::string::npos; };

    static const char* danger[] = {
        "rm -rf", "rm -r ", "rm -fr", "rmdir", "git push --force", "push -f", "--force", "git reset --hard",
        "git clean -f", "drop table", "drop database", "delete from", "truncate", "mkfs", "dd if=", "> /dev/",
        "chmod -r 777", "chown -r", "kill -9", "killall", "shutdown", "reboot", "curl | sh", "curl | bash",
        "wget | sh", "| sudo", "sudo rm", ":(){", "format c:", "del /s", "rd /s", "terraform destroy",
        "kubectl delete", "docker system prune", "docker rm", "nvs_flash_erase", "factory reset",
    };
    static const char* caution[] = {
        "sudo", "git push", "git commit", "git rebase", "git checkout .", "git stash", "npm publish", "pip install",
        "npm install", "brew install", "apt install", "cargo publish", "idf.py flash", "esptool", "write_flash",
        "erase_flash", "ssh ", "scp ", "rsync", "chmod", "chown", "mv ", "kubectl apply", "docker run",
        "systemctl", "launchctl", "crontab", "> ~/", ">> ~/", "curl -x post", "curl -d",
    };
    for (auto* n : danger)  if (has(n)) return Risk::Danger;
    for (auto* n : caution) if (has(n)) return Risk::Caution;
    return Risk::None;
}

const char* AppClaudeBuddy::moodName(Mood m)
{
    switch (m) {
        case Mood::Sleep:     return "sleep";
        case Mood::Idle:      return "idle";
        case Mood::Busy:      return "busy";
        case Mood::Attention: return "attention";
        case Mood::Celebrate: return "celebrate";
        case Mood::Heart:     return "heart";
    }
    return "?";
}

std::string AppClaudeBuddy::fit(const std::string& s, size_t max)
{
    if (s.size() <= max) return s;
    // Avoid cutting a UTF-8 sequence in half
    size_t cut = max;
    while (cut > 0 && (static_cast<uint8_t>(s[cut]) & 0xC0) == 0x80) cut--;
    return s.substr(0, cut) + "…";
}

// ── UI ────────────────────────────────────────────────────────────────────────

void AppClaudeBuddy::createUi()
{
    // Must be called with LvglLockGuard held.
    _btn_approve = std::make_unique<Button>(lv_screen_active());
    _btn_approve->setSize(120, 44);
    _btn_approve->align(LV_ALIGN_BOTTOM_LEFT, 14, -14);
    _btn_approve->setBgColor(lv_color_hex(0x2E9E5B));
    _btn_approve->setRadius(12);
    _btn_approve->label().setText("Approve");
    _btn_approve->label().setTextFont(&lv_font_montserrat_16);
    _btn_approve->label().setTextColor(lv_color_hex(0xFFFFFF));
    _btn_approve->onClick().connect([this]() { _approve_clicked = true; });
    _btn_approve->setHidden(true);

    _btn_deny = std::make_unique<Button>(lv_screen_active());
    _btn_deny->setSize(120, 44);
    _btn_deny->align(LV_ALIGN_BOTTOM_RIGHT, -14, -14);
    _btn_deny->setBgColor(lv_color_hex(0xC0392B));
    _btn_deny->setRadius(12);
    _btn_deny->label().setText("Deny");
    _btn_deny->label().setTextFont(&lv_font_montserrat_16);
    _btn_deny->label().setTextColor(lv_color_hex(0xFFFFFF));
    _btn_deny->onClick().connect([this]() { _deny_clicked = true; });
    _btn_deny->setHidden(true);

    _overlay = std::make_unique<Container>(lv_screen_active());
    _overlay->setSize(320, 240);
    _overlay->setAlign(LV_ALIGN_CENTER);
    _overlay->setBgColor(lv_color_hex(0x101010));
    _overlay->setBgOpa(LV_OPA_90);
    _overlay->setBorderWidth(0);
    _overlay->setRadius(0);
    _overlay->setPaddingAll(10);
    _overlay->setScrollbarMode(LV_SCROLLBAR_MODE_OFF);
    _overlay->onClick().connect([this]() { _overlay_clicked = true; });

    _overlay_label = std::make_unique<Label>(_overlay->get());
    _overlay_label->setTextFont(&lv_font_montserrat_14);
    _overlay_label->setTextColor(lv_color_hex(0xEDEDED));
    _overlay_label->setSize(300, 112);              // 7 lines of the 14 px font, never past the chart
    _overlay_label->setLongMode(LV_LABEL_LONG_CLIP);
    _overlay_label->align(LV_ALIGN_TOP_LEFT, 0, 0);
    _overlay_label->setText("");

    // 7-day token chart at the bottom of the overlay
    _chart_title = std::make_unique<Label>(_overlay->get());
    _chart_title->setTextFont(&lv_font_montserrat_14);
    _chart_title->setTextColor(lv_color_hex(0x9A9A9A));
    _chart_title->setText("Claude output tokens per day (last 7 days)");
    _chart_title->align(LV_ALIGN_TOP_LEFT, 0, 114);

    _chart = lv_chart_create(_overlay->get());
    lv_obj_set_size(_chart, 300, 70);
    lv_obj_align(_chart, LV_ALIGN_TOP_MID, 0, 132);
    lv_chart_set_type(_chart, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(_chart, buddy::BuddyStore::DAYS);
    lv_chart_set_div_line_count(_chart, 0, 0);
    lv_chart_set_range(_chart, LV_CHART_AXIS_PRIMARY_Y, 0, 1000);
    lv_obj_set_style_bg_color(_chart, lv_color_hex(0x1C1C1C), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(_chart, LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_set_style_border_width(_chart, 0, LV_PART_MAIN);
    lv_obj_set_style_radius(_chart, 6, LV_PART_MAIN);
    lv_obj_set_style_pad_all(_chart, 4, LV_PART_MAIN);
    lv_obj_set_style_pad_column(_chart, 10, LV_PART_MAIN);   // gap between days
    lv_obj_set_style_pad_column(_chart, 0, LV_PART_ITEMS);   // series overlap (one bar per day)
    lv_obj_set_style_radius(_chart, 3, LV_PART_ITEMS);
    lv_obj_set_style_bg_opa(_chart, LV_OPA_COVER, LV_PART_ITEMS);
    lv_obj_remove_flag(_chart, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_remove_flag(_chart, LV_OBJ_FLAG_CLICKABLE);
    _series_past  = lv_chart_add_series(_chart, lv_color_hex(0x6E5A4E), LV_CHART_AXIS_PRIMARY_Y);
    _series_today = lv_chart_add_series(_chart, lv_color_hex(THEME_PRIMARY), LV_CHART_AXIS_PRIMARY_Y);

    for (int i = 0; i < buddy::BuddyStore::DAYS; i++) {
        _day_labels[i] = std::make_unique<Label>(_overlay->get());
        _day_labels[i]->setTextFont(&lv_font_montserrat_14);
        _day_labels[i]->setTextColor(lv_color_hex(0x9A9A9A));
        _day_labels[i]->setText("-");
        // 300 px wide chart, 7 slots → centre of slot i
        _day_labels[i]->align(LV_ALIGN_BOTTOM_LEFT, 4 + i * 300 / 7 + 300 / 14 - 5, 0);

        // value printed on top of each bar, so a bar reads on its own
        _bar_values[i] = std::make_unique<Label>(_overlay->get());
        _bar_values[i]->setTextFont(&lv_font_montserrat_14);
        _bar_values[i]->setTextColor(lv_color_hex(0xEDEDED));
        _bar_values[i]->setText("");
        _bar_values[i]->setWidth(300 / 7);
        _bar_values[i]->setTextAlign(LV_TEXT_ALIGN_CENTER);
        _bar_values[i]->align(LV_ALIGN_TOP_LEFT, i * 300 / 7, 132);
    }
    _overlay->setHidden(true);

    // Clock face (idle for a long time)
    _clock_panel = std::make_unique<Container>(lv_screen_active());
    _clock_panel->setSize(320, 240);
    _clock_panel->setAlign(LV_ALIGN_CENTER);
    _clock_panel->setBgColor(lv_color_hex(0x0A0A0A));
    _clock_panel->setBgOpa(LV_OPA_COVER);
    _clock_panel->setBorderWidth(0);
    _clock_panel->setRadius(0);
    _clock_panel->setPaddingAll(0);
    _clock_panel->removeFlag(LV_OBJ_FLAG_SCROLLABLE);
    _clock_panel->onClick().connect([this]() { _screen_clicked = true; });

    _clock_time = std::make_unique<Label>(_clock_panel->get());
    _clock_time->setTextFont(&MontserratSemiBold26);
    _clock_time->setTextColor(lv_color_hex(THEME_PRIMARY));
    _clock_time->setText("--:--");
    _clock_time->align(LV_ALIGN_CENTER, 0, -14);
    // No large font in this build: scale the 26 px face ×2.6 (renders as a bitmap)
    lv_obj_set_style_transform_scale(_clock_time->get(), 666, 0);
    lv_obj_set_style_transform_pivot_x(_clock_time->get(), LV_PCT(50), 0);
    lv_obj_set_style_transform_pivot_y(_clock_time->get(), LV_PCT(50), 0);

    _clock_date = std::make_unique<Label>(_clock_panel->get());
    _clock_date->setTextFont(&lv_font_montserrat_16);
    _clock_date->setTextColor(lv_color_hex(0x9A9A9A));
    _clock_date->setText("");
    _clock_date->align(LV_ALIGN_CENTER, 0, 52);
    _clock_panel->setHidden(true);

    // Pairing passkey panel (shown while macOS asks for the 6-digit code)
    _pair_panel = std::make_unique<Container>(lv_screen_active());
    _pair_panel->setSize(250, 112);
    _pair_panel->setAlign(LV_ALIGN_CENTER);
    _pair_panel->setBgColor(lv_color_hex(THEME_DARK));
    _pair_panel->setBgOpa(LV_OPA_COVER);
    _pair_panel->setBorderWidth(3);
    _pair_panel->setBorderColor(lv_color_hex(THEME_PRIMARY));
    _pair_panel->setRadius(18);
    _pair_panel->setPaddingAll(8);
    _pair_panel->removeFlag(LV_OBJ_FLAG_SCROLLABLE);

    _pair_title = std::make_unique<Label>(_pair_panel->get());
    _pair_title->setTextFont(&lv_font_montserrat_16);
    _pair_title->setTextColor(lv_color_hex(0xEDEDED));
    _pair_title->setText("Pairing code");
    _pair_title->align(LV_ALIGN_TOP_MID, 0, 4);

    _pair_code = std::make_unique<Label>(_pair_panel->get());
    _pair_code->setTextFont(&MontserratSemiBold26);
    _pair_code->setTextColor(lv_color_hex(THEME_PRIMARY));
    _pair_code->setText("");
    _pair_code->align(LV_ALIGN_BOTTOM_MID, 0, -8);
    _pair_panel->setHidden(true);
}

void AppClaudeBuddy::showClock(bool show)
{
    // Must be called with LvglLockGuard held.
    if (!_clock_panel) return;
    _clock_shown = show;
    if (show) {
        mclog::tagInfo(TAG, "clock mode on");
        updateClock();
        showOverlay(false);
        _clock_panel->setHidden(false);
        _clock_panel->moveForeground();
        if (GetStackChan().hasAvatar()) GetStackChan().avatar().setSpeech("");
    } else {
        mclog::tagInfo(TAG, "clock mode off");
        _clock_panel->setHidden(true);
        refreshSpeech();
    }
}

void AppClaudeBuddy::updateClock()
{
    // Must be called with LvglLockGuard held.
    if (!_clock_time || !_clock_date) return;
    _clock_tick = GetHAL().millis();
    time_t now  = time(nullptr);
    struct tm t;
    localtime_r(&now, &t);
    char tbuf[8], dbuf[40];
    strftime(tbuf, sizeof(tbuf), "%H:%M", &t);
    strftime(dbuf, sizeof(dbuf), "%a %d %b", &t);
    _clock_time->setText(tbuf);
    _clock_date->setText(dbuf);
}

void AppClaudeBuddy::showPasskey(uint32_t passkey)
{
    // Must be called with LvglLockGuard held.
    if (!_pair_panel || !_pair_code) return;
    if (passkey == 0) {
        _pair_panel->setHidden(true);
        refreshSpeech();
        return;
    }
    char buf[16];
    snprintf(buf, sizeof(buf), "%06lu", (unsigned long)passkey);
    _pair_code->setText(buf);
    showOverlay(false);
    _pair_panel->setHidden(false);
    _pair_panel->moveForeground();
    if (GetStackChan().hasAvatar()) {
        GetStackChan().avatar().setSpeech("Type this code on your Mac");
    }
}

void AppClaudeBuddy::destroyUi()
{
    _clock_date.reset();
    _clock_time.reset();
    _clock_panel.reset();
    for (auto& l : _day_labels) l.reset();
    for (auto& l : _bar_values) l.reset();
    _chart_title.reset();
    if (_chart) {
        lv_obj_delete(_chart);
        _chart = nullptr;
    }
    _pair_code.reset();
    _pair_title.reset();
    _pair_panel.reset();
    _overlay_label.reset();
    _overlay.reset();
    _btn_approve.reset();
    _btn_deny.reset();
}

void AppClaudeBuddy::showDecisionButtons(bool show)
{
    if (!_btn_approve || !_btn_deny) return;
    _btn_approve->setHidden(!show);
    _btn_deny->setHidden(!show);
    if (show) {
        _btn_approve->moveForeground();
        _btn_deny->moveForeground();
        showOverlay(false);
    }
}

void AppClaudeBuddy::showOverlay(bool show)
{
    if (!_overlay) return;
    if (show) {
        refreshOverlay();
        _overlay->setHidden(false);
        _overlay->moveForeground();
        _overlay_until = GetHAL().millis() + OVERLAY_MS;
    } else {
        _overlay->setHidden(true);
        _overlay_until = 0;
    }
}

void AppClaudeBuddy::refreshOverlay()
{
    if (!_overlay || !_overlay_label || _overlay->hasFlag(LV_OBJ_FLAG_HIDDEN)) return;

    auto& link = buddy::BuddyLink::instance();
    std::string t;
    t.reserve(512);

    t += _store.name;
    if (!_store.owner.empty()) t += "  ·  " + _store.owner;
    t += link.isReady() ? "  ·  linked\n" : (link.isConnected() ? "  ·  connecting\n" : "  ·  offline\n");

    char buf[96];
    snprintf(buf, sizeof(buf), "Sessions %d  (run %d / wait %d)\n", _snap.total, _snap.running, _snap.waiting);
    t += buf;
    snprintf(buf, sizeof(buf), "Tokens %lu  today %lu  Lv %d\n", (unsigned long)_snap.tokens,
             (unsigned long)_snap.tokens_today, _level < 0 ? 0 : _level);
    t += buf;
    snprintf(buf, sizeof(buf), "OK %d  Deny %d  Fast %d  Naps %d\n", _store.appr, _store.deny, _store.vel,
             _store.nap);
    t += buf;

    if (_snap.prompt.present) {
        t += std::string(_prompt_risk == Risk::Danger ? "!! DANGER " : _prompt_risk == Risk::Caution ? "! Careful " : "? ") +
             fit(_snap.prompt.tool + " " + _snap.prompt.hint, 40) + "\n";
    }
    if (!_snap.msg.empty()) t += "> " + fit(_snap.msg, 44) + "\n";
    if (!_snap.entries.empty()) {
        t += "  " + fit(_snap.entries.front(), 44) + "\n";  // one line; the chart needs the rest
    }

    _overlay_label->setText(t);
    refreshChart();
}

void AppClaudeBuddy::refreshChart()
{
    if (!_chart) return;
    constexpr int N = buddy::BuddyStore::DAYS;

    uint32_t maxv = 1000;
    for (int i = 0; i < N; i++) maxv = std::max(maxv, _store.days[i].tokens);
    // round the axis up to a friendly number
    uint32_t step = 1000;
    while (step * 10 < maxv) step *= 10;
    uint32_t range = ((maxv + step - 1) / step) * step;
    lv_chart_set_range(_chart, LV_CHART_AXIS_PRIMARY_Y, 0, static_cast<int32_t>(range));

    static const char* wd = "SMTWTFS";
    for (int i = 0; i < N; i++) {
        // chart slot i ← days[N-1-i] (oldest left, today right)
        const auto& d = _store.days[N - 1 - i];
        int32_t v     = d.date ? static_cast<int32_t>(d.tokens) : LV_CHART_POINT_NONE;
        bool is_today = (N - 1 - i) == 0 && d.date != 0;
        lv_chart_set_value_by_id(_chart, _series_past, i, is_today ? LV_CHART_POINT_NONE : v);
        lv_chart_set_value_by_id(_chart, _series_today, i, is_today ? v : LV_CHART_POINT_NONE);

        char lbl[2] = {'-', 0};
        if (d.date) {
            struct tm tmv = {};
            tmv.tm_year   = static_cast<int>(d.date / 10000) - 1900;
            tmv.tm_mon    = static_cast<int>((d.date / 100) % 100) - 1;
            tmv.tm_mday   = static_cast<int>(d.date % 100);
            tmv.tm_hour   = 12;
            mktime(&tmv);
            lbl[0] = wd[tmv.tm_wday];
        }
        if (_day_labels[i]) {
            _day_labels[i]->setText(lbl);
            _day_labels[i]->setTextColor(lv_color_hex(is_today ? THEME_PRIMARY : 0x9A9A9A));
        }
        if (_bar_values[i]) {
            if (d.date) {
                // chart at y=132, 70 px tall, 4 px padding → bar top; label sits just above it
                const int inner_h = 70 - 8;
                int bar_top       = 132 + 4 + inner_h - static_cast<int>(static_cast<uint64_t>(d.tokens) * inner_h / range);
                int y             = std::max(132, bar_top - 16);
                _bar_values[i]->setText(compactNumber(d.tokens));
                _bar_values[i]->align(LV_ALIGN_TOP_LEFT, i * 300 / 7, y);
            } else {
                _bar_values[i]->setText("");
            }
        }
    }
    lv_chart_refresh(_chart);
}

std::string AppClaudeBuddy::compactNumber(uint32_t v)
{
    char buf[16];
    if (v >= 1000000)    snprintf(buf, sizeof(buf), "%.1fM", v / 1000000.0);
    else if (v >= 100000) snprintf(buf, sizeof(buf), "%luk", (unsigned long)(v / 1000));
    else if (v >= 1000)   snprintf(buf, sizeof(buf), "%.1fk", v / 1000.0);
    else                  snprintf(buf, sizeof(buf), "%lu", (unsigned long)v);
    return buf;
}

uint32_t AppClaudeBuddy::localDate()
{
    time_t now = time(nullptr);
    struct tm t;
    localtime_r(&now, &t);
    if (t.tm_year + 1900 < 2020) return 0;  // clock not synced yet
    return static_cast<uint32_t>((t.tm_year + 1900) * 10000 + (t.tm_mon + 1) * 100 + t.tm_mday);
}

// ── Sleep / backlight ─────────────────────────────────────────────────────────

void AppClaudeBuddy::noteActivity(const char* reason)
{
    mclog::tagInfo(TAG, "activity: {}", reason);
    _last_activity_ms = GetHAL().millis();
    if (_dimmed) {
        _dimmed = false;
        GetHAL().setBackLightBrightness(75);
    }
}

void AppClaudeBuddy::checkDim()
{
    // Dim only while asleep; an active bridge keeps the screen on
    if (_mood != Mood::Sleep) {
        if (_dimmed) noteActivity();
        return;
    }
    if (!_dimmed && static_cast<int32_t>(GetHAL().millis() - _last_activity_ms) >= static_cast<int32_t>(DIM_AFTER_MS)) {
        _dimmed = true;
        GetHAL().setBackLightBrightness(20);
    }
}
